# This is a basic workflow to help you get started with Actions

name: CI-main

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Run main
        run: echo Hello, world!

      - name: Git Tag
        run : |
          git tag satging/$(git rev-list --count HEAD)
          git push origin satging/$(git rev-list --count HEAD)
