# This is a basic workflow to help you get started with Actions

name: CI-main

on:
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run main
        run: echo Hello, world!
