# This is a basic workflow to help you get started with Actions

name: CI-RELEASE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGEX_STAGING_BRANCH: '^refs/tags/staging/(?!.*\*).+$'
    if: env.REGEX_STAGING_BRANCH && env.REGEX_STAGING_BRANCH != '' && env.REGEX_STAGING_BRANCH =~ github.ref
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Run realse
        run: echo Hello, world!
